const applications = {
    "Anesthesia": { prefix: 112, naming: "OLVG AN" },
    "ASAP": { prefix: 160, naming: "OLVG SEH" },
    "Beacon": { prefix: 115, naming: "OLVG ONC" },
    "Bugsy": { prefix: 191, naming: "OLVG IFPR" },
    "Cadence": { prefix: 117, naming: "OLVG ES" },
    "Cupid": { prefix: 118, naming: "OLVG CV" },
    "Data Courier": { prefix: 192, naming: "OLVG DC" },
    "DBC": { prefix: 108, naming: "OLVG DBC" },
    "EpicCare Inpatient": { prefix: 304, naming: "OLVG INP" },
    "EpicCare Ambulatory": { prefix: 210, naming: "OLVG AMB" },
    "EpicCare Link": { prefix: 110, naming: "OLVG LINK" },
    "Grand Central": { prefix: 310, naming: "OLVG ADT" },
    "HIM": { prefix: 130, naming: "OLVG HIM" },
    "Identity": { prefix: 135, naming: "OLVG ID" },
    "Kaleidoscope": { prefix: 210, naming: "OLVG KAL" },
    "MyChart": { prefix: 140, naming: "OLVG MC" },
    "Optime": { prefix: 107, naming: "OLVG OK" },
    "Orders": { prefix: 222, naming: "OLVG ORD" },
    "Prelude": { prefix: 310, naming: "OLVG REG" },
    "Radiant": { prefix: 156, naming: "OLVG RAD" },
    "Reporting": { prefix: 444, naming: "OLVG RW" },
    "Research": { prefix: 888, naming: "OLVG RSH" },
    "Stork": { prefix: 102, naming: "OLVG VERLOS" },
    "Willow/Apotheek": { prefix: 408, naming: "OLVG RX" },
    "Zorgpaden": { prefix: 555, naming: "OLVG ZP" }
};